from PIL import Image,ImageOps
import os,sys,bitplanelib,math

from shared import *

sprite_context_list = ["intro","level_1","level_2","level_3","level_3_base","level_4"]
bg_tile_context_list = ["level_1_1","level_1_2","level_2","level_3_1","level_3_2","level_3_base",
"level_4","outro"]
sprite_context_list = ["level_1"]
bg_tile_context_list = []

sprite_names = get_sprite_names()

mirror_sprites = get_mirror_sprites()

nb_planes = 7
max_nb_sprite_colors = 1<<(nb_planes-1)
max_nb_bg_tile_colors = max_nb_sprite_colors

max_used_nb_bg_tile_colors = max_used_nb_sprite_colors = max_nb_sprite_colors

possible_hw_sprites = set()

# uncomment to disable hw sprites completely
#possible_hw_sprites = set()

magenta = (254,0,254)


generated_message = "* generated by convert_graphics.py\n"

if dump_it:
    if not os.path.exists(dump_dir):
        os.mkdir(dump_dir)
        with open(os.path.join(dump_dir,".gitignore"),"w") as f:
            f.write("*")


with (this_dir / "grouped.json").open() as f:
    grouped = json.load(f)

grouped = {int(k,16):[int(d,16) for d in v] for k,v in grouped.items()}

for k,v in grouped.items():
    if len(v)==1:
        group_sprite_pairs[k]=v[0]
        group_sprite_pairs[k+0x1000]=v[0]+0x1000
    elif len(v)==2:
        group_sprite_triplets[k]=v
    elif len(v)==3:
        group_sprite_quadruplets[k]=v


def ensure_empty(d):
    if d.exists():
        for f in os.listdir(d):
            os.remove(os.path.join(d,f))
    else:
        d.mkdir(parents=True)

def is_pre_mirrored(prefix,context):
    pc = sprites_per_level.get(prefix)
    if not pc:
        # not listed: pre-mirror to avoid issues
        return True
    pre_mirror = pc["pre_mirror"]
    if pre_mirror is None:
        # never pre-mirror
        return False
    if pre_mirror == True:
        # always pre-mirror
        return True
    # pre-mirror only in some levels
    return context in pre_mirror

def is_in_level(prefix,context):
    pc = sprites_per_level.get(prefix)
    if not pc:
        # not listed: in all levels & contextes
        return True
    levels = pc["levels"]
    if not levels:
        # also included in all levels
        return True
    if context is None:
        # context none: global, pc not found or : include
        return not levels
    # included only if context defined and matches
    return not levels or context in levels

def get_sprite_name(i):
    return sprite_names.get(i,sprite_names.get(i-0x1000,"bob"))

def dump_bob_layer(sprite_table,f,relative_root=None):
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(sprite_table):
        f.write("\t.long\t")
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = get_sprite_name(i)
            f.write(f"{prefix}_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")

        else:
            f.write("0")
        f.write("\n")


    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = get_sprite_name(i)
            f.write(f"{prefix}_{i:02x}:\n")
            for j,t in enumerate(tile_entry):
                f.write("\t.long\t")
                if t:
                    f.write(f"{prefix}_{i:02x}_{j:02x}")
                    if relative_root:
                        f.write(f"-{relative_root}")
                else:
                    f.write("0")
                f.write("\n")

    needed_bob_bitplanes = set()

    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = get_sprite_name(i)
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    height = 0

                    offset = 0
                    for orientation,_ in plane_orientations:
                        if orientation in t:
                            width = t[orientation]["width"]
                            height = t[orientation]["height"]
                            offset = t[orientation]["y_start"]
                            break
                    else:
                        raise Exception(f"height not found for {name}!!")
                    nonzero_written = False
                    for orientation,_ in plane_orientations:
                        # loop for this, this sucks
                        if orientation == "standard":
                            f.write("* orientation={}\n".format(orientation))
                            active_planes = 0
                            bitplanes = t[orientation]["bitplanes"]

                            for j,bitplane_id in enumerate(bitplanes):
                                if bitplane_id:
                                    active_planes |= 1<<j
                            bitplane_info = f"\t.word\t{height},{width},{offset},0x{active_planes:x}  | height,width,offset,active_planes\n"
                            f.write(bitplane_info)
                            for bitplane_id in bitplanes:
                                f.write("\t.long\t")
                                if bitplane_id:
                                    nonzero_written = True
                                    bob_bitplane_ptr = f"bob_plane_{bitplane_id:02d}"
                                    needed_bob_bitplanes.add(bitplane_id)
                                    f.write(bob_bitplane_ptr)
                                    if relative_root:
                                        f.write(f"-{relative_root}")
                                else:
                                    f.write("0")
                                f.write("\n")

                    if False: #nonzero_written and is_pre_mirrored(prefix,context):
                        # tell the game engine that it has to mirror the bitplanes
                        # at start/file load and put them here
                        # (except if tile has 0 data because it's blank)

                        f.write("* mirrored bitplanes pointers (inc. mask) go here\n")
                        for _ in bitplanes:
                            f.write(f"\t.long\t-1\n")
                    else:
                        # tell the game engine that it has to mirror in-place
                        f.write("\t.word\t-2    | bitplanes above will be mirrored in-place\n\n")

    if not relative_root:
        f.write("\t.section\t.datachip\n")

    for k,v in bob_plane_cache.items():
        if v in needed_bob_bitplanes:
            f.write(f"""
\t.word\t0    | plane {v:02d} orientation
bob_plane_{v:02d}:""")
            dump_asm_bytes(k,f)

def load_tileset(image_name,palette_index,width,height,tileset_name,dumpdir,
dump=False,name_dict=None,cluts=None,tile_number=0,is_bob=False,size_table=None):

##    if isinstance(image_name,str):
##        full_image_path = os.path.join(this_dir,os.path.pardir,"sheets",
##                            tile_type,image_name)
##        tiles_1 = Image.open(full_image_path)
##    else:
    tiles_1 = image_name
    nb_rows = tiles_1.size[1] // height
    nb_cols = tiles_1.size[0] // width


    tileset_1 = []

    if dump:
        dump_subdir = dumpdir / tileset_name
        if palette_index == 0 and tile_number == 0:
            ensure_empty(dump_subdir)

    palette = set()

    for j in range(nb_rows):
        for i in range(nb_cols):

            if cluts is not None and (tile_number not in cluts or palette_index not in cluts[tile_number]):
                # no clut declared for that tile
                tileset_1.append(None)
            else:

                img = Image.new("RGB",(width,height))
                img.paste(tiles_1,(-i*width,-j*height))

                # only consider colors of used tiles
                palette.update(set(bitplanelib.palette_extract(img)))


                tileset_1.append(img)
                # dump tiles
                if not is_bob and dump:
                    img = ImageOps.scale(img,5,resample=Image.Resampling.NEAREST)
                    if name_dict:
                        name = name_dict.get(tile_number,"unknown")
                    else:
                        name = "unknown"

                    img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))

            tile_number += 1

    if is_bob:
        # double the tileset as sometimes sprite can have single size, double size or both in different contexts
        tileset_length = len(tileset_1)
        tileset_1 += [None]*tileset_length

        # rework & dump grouped / non grouped sprites
        # rework tiles which are grouped
        # first pass create double height clones in index*2
        missing_tile = False
        for tile_number,wtile in enumerate(tileset_1):

            # create hardware Y-grouped tiles
            if tile_number == tileset_length:
                break
            if wtile:
                tile_size = size_table.get(tile_number,0)
                if tile_size & 2:
                    # Y group
                    other_tile_index = tile_number+1
                    other_tile = tileset_1[other_tile_index]
                    if not other_tile:
                        missing_tile = True
                        print(f"Warning: YHW size: pair: palette_index: {palette_index}: 0x{tile_number:02x} ({get_sprite_name(tile_number)}), size_mask={tile_size} ok but other tile index 0x{other_tile_index:02x} not found")
                    else:
                        new_tile = Image.new("RGB",(wtile.size[0],wtile.size[1]*2))
                        new_tile.paste(wtile,box=(0,0))
                        new_tile.paste(other_tile,box=(0,16))
                        tileset_1[tile_number+tileset_length] = new_tile  # insert tile in the upper double Y space (tile id + 0x1000)
                        wtile = new_tile
                if tile_size & 1 == 0:
                    # now remove the tiles that don't have single size from tileset, else they're dumped
                    # at it eats a lot of memory. We needed them to be loaded to be able to compose double height
                    # but that's the only reason
                    tileset_1[tile_number] = None  # discard if single size is not declared

        if missing_tile:
            raise Exception("Missing tile(s) cannot continue")
        for tile_number,wtile in enumerate(tileset_1):
            # software grouped tiles, not enabled, and wrong too: it doesn't follow a logic, it needs to be specified by hand
            if wtile:
                other_tile_index = group_sprite_pairs.get(tile_number)

                if other_tile_index is not None:
                    other_tile = tileset_1[other_tile_index]
                    if not other_tile:
                        raise Exception(f"pair: 0x{tile_number:02x} ok but other tile index 0x{other_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*2,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(other_tile,(wtile.size[0],0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[other_tile_index] = None  # discard
                    wtile = new_tile

##                elif False and tile_number in group_sprite_triplets:
##                    # change wtile, fetch code +1
##                    central_tile_index = tile_number+1
##                    central_tile = tileset_1[central_tile_index]
##                    right_tile_index = central_tile_index+1
##                    right_tile = tileset_1[right_tile_index]
##                    if not central_tile:
##                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
##                    if not right_tile:
##                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
##                    new_tile = Image.new("RGB",(wtile.size[0]*3,wtile.size[1]))
##
##                    new_tile.paste(wtile)
##
##                    new_tile.paste(central_tile,(wtile.size[0],0))
##                    new_tile.paste(right_tile,(wtile.size[0]*2,0))
##                    tileset_1[tile_number] = new_tile
##                    tileset_1[central_tile_index] = None  # discard
##                    tileset_1[right_tile_index] = None  # discard
##                    wtile = new_tile
##
##                elif False and tile_number in group_sprite_quadruplets:
##                    # change wtile, fetch code +1
##                    central_tile_index = tile_number+1
##                    central_tile_1 = tileset_1[central_tile_index]
##                    central_tile_2 = tileset_1[central_tile_index+1]
##                    right_tile_index = central_tile_index+2
##                    right_tile = tileset_1[right_tile_index]
##                    if not central_tile_1:
##                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
##                    if not central_tile_2:
##                        raise Exception(f"triplet: central tile index 0x{central_tile_index+1:02x} not found")
##                    if not right_tile:
##                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
##                    new_tile = Image.new("RGB",(wtile.size[0]*4,wtile.size[1]))
##
##                    new_tile.paste(wtile)
##
##                    new_tile.paste(central_tile_1,(wtile.size[0],0))
##                    new_tile.paste(central_tile_2,(wtile.size[0]*2,0))
##                    new_tile.paste(right_tile,(wtile.size[0]*3,0))
##                    tileset_1[tile_number] = new_tile
##                    tileset_1[central_tile_index] = None  # discard
##                    tileset_1[central_tile_index+1] = None  # discard
##                    tileset_1[right_tile_index] = None  # discard
##                    wtile = new_tile

        for tile_number,wtile in enumerate(tileset_1):
            if dump_it and wtile:
                bigprefix = "_xgrouped" if (wtile.size[0]>0x10) else ""
                img = ImageOps.scale(wtile,5,resample=Image.Resampling.NEAREST)
                if sprite_names:
                    name = sprite_names.get(tile_number,sprite_names.get(tile_number-0x1000,"unknown"))
                else:
                    name = "unknown"

                img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}{bigprefix}.png"))



    return sorted(set(palette)),tileset_1


plane_orientations = [("standard",lambda x:x),
("flip",ImageOps.flip),
("mirror",ImageOps.mirror),
("flip_mirror",lambda x:ImageOps.flip(ImageOps.mirror(x)))]

def asm2bin(bank):
    banko = bank.parent / f"{bank.stem}.o"
    banke = bank.parent / f"{bank.stem}"
    cmd = ["m68k-amigaos-as","-o",banko,bank]
    subprocess.run(cmd,check=True)
    # link the result. Not necessary when generation is OK, but
    # not everything is solved (dangling references), we'll detect it
    cmd = ["m68k-amigaos-ld","-o",banke,banko]
    subprocess.run(cmd,check=True)
    bankbin = data_dir / f"{bank.stem}"
    cmd = ["m68k-amigaos-objcopy","-O","binary",banke,bankbin]
    subprocess.run(cmd,check=True)


def read_tileset(img_set_list,palette,plane_orientation_flags,cache,is_bob,nb_cluts,mask_color,next_cache_id = 1):
    nb_planes = int(math.log2(len(palette)))

    tile_table = []
    for n,img_set in enumerate(img_set_list):
        tile_entry = []
        for i,tile in enumerate(img_set):
            entry = dict()
            if tile:

                for b,(plane_name,plane_func) in zip(plane_orientation_flags,plane_orientations):
                    bitplane_sprite_data = None
                    if b:

                        actual_nb_planes = nb_planes

                        # most sprites aren't mirrored. Save a lot of memory!
                        if plane_func == ImageOps.mirror and i not in mirror_sprites:
                            continue

                        wtile = plane_func(tile)

                        if is_bob:
                            actual_nb_planes += 1


                            # only 4 planes + mask => 5 planes
                            orig_wtile = wtile
                            y_start,wtile = bitplanelib.autocrop_y(wtile,mask_color=magenta)
                            height = wtile.size[1]
                            width = wtile.size[0]//8 + 2
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,generate_mask=True,mask_color=mask_color)
                            # add sprite data if eligible: player frame, not mirrored

##                            if i in possible_hw_sprites:
##                                # using original, uncropped bitplane data
##                                bitplane_sprite_data = bitplanelib.palette_image2attached_sprites(orig_wtile,None,palette,
##                                sprite_fmode=2,with_control_words=True)
##                                # void the blitter data
##                                bitplane_data = b''
                        else:
                            # 4 planes, no mask
                            height = 8
                            width = 1
                            y_start = 0
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,mask_color=mask_color)

                        plane_size = len(bitplane_data) // actual_nb_planes
                        bitplane_plane_ids = []
                        for j in range(actual_nb_planes):
                            offset = j*plane_size
                            bitplane = bitplane_data[offset:offset+plane_size]

                            cache_id = cache.get(bitplane)
                            if cache_id is not None:
                                bitplane_plane_ids.append(cache_id)
                            else:
                                if any(bitplane):
                                    cache[bitplane] = next_cache_id
                                    bitplane_plane_ids.append(next_cache_id)
                                    next_cache_id += 1
                                else:
                                    bitplane_plane_ids.append(0)  # blank
                        entry[plane_name] = {"width":width,"height":height,"y_start":y_start,"bitplanes":bitplane_plane_ids}
                        if bitplane_sprite_data:
                            entry[plane_name]["sprdat"] = bitplane_sprite_data

            tile_entry.append(entry)

        tile_table.append(tile_entry)

    new_tile_table = [[[] for _ in range(nb_cluts)] for _ in range(len(tile_table[0]))]

    # reorder/transpose. We have 16 * 256 we need 256 * 16
    for i,u in enumerate(tile_table):
        for j,v in enumerate(u):
            new_tile_table[j][i] = v

    return new_tile_table,next_cache_id


def dump_tile_layer(f,tile_table,prefix,relative_root=None):
    item_decl = "\t.long\t"
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(tile_table):
        f.write(item_decl)
        if tile_entry and any(tile_entry):
            f.write(f"{prefix}_tile_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")
        else:
            f.write("0")
        f.write("\n")

    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            rr = f"{prefix}_tile_{i:02x}"
            f.write(f"{rr}:\n")
            for j,t in enumerate(tile_entry):
                f.write(item_decl)
                if t:
                    f.write(f"{prefix}_tile_{i:02x}_{j:02x}")
                    if relative_root:
                        f.write(f"-{relative_root}")
                else:
                    f.write("0")
                f.write("\n")


    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}_tile_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    for orientation,_ in plane_orientations:
                        f.write("* orientation={}\n".format(orientation))
                        if orientation in t:
                            data = t[orientation]
                            for bitplane_id in data["bitplanes"]:
                                f.write(item_decl)
                                if bitplane_id:
                                    f.write(f"tile_plane_{bitplane_id:02d}")
                                    if relative_root:
                                        f.write(f"-{relative_root}")
                                else:
                                    f.write("0")
                                f.write("\n")
                            if len(t)==1:
                                # optim: only standard
                                break
                        else:
                            for _ in range(nb_planes):
                                f.write(f"{item_decl}0\n")





# foreground tiles doesn't seem to change palette (we'll see) but context selection allows to avoid too much global
# quantization, so the colors won't look so washed up
fg_tile_sheet_dict = {i:Image.open(sheets_path / "fg_tiles" / f"pal_{i:02x}.png") for i in range(FG_NB_CLUTS)}


#######################################################
## foreground tiles: only 2 cases: title and in-game ##
#######################################################


context_list = ["title","game","highscores"]
for context in context_list:

    context = pathlib.Path(context)
    fg_tile_set_list = []

    fg_tile_cluts = {}


    read_used_tiles(context/"fg_used_tiles",fg_tile_cluts,FG_NB_TILES,FG_NB_CLUTS)


    if dump_it:
        (dump_dir / context).mkdir(exist_ok=True)
        with open(dump_dir / context / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)



    # now gather all cluts used by letter/digit tiles, logging probably
    # missed some
    # some tiles are hard to display... We know they are there, we force them
    # instead of trying to trigger them by playing to death :)

    alphanum_tile_codes = [x-0x20 for x in list(range(ord('0'),ord('9')+1)) + list(range(ord('A'),ord('Z')+1))]
    used_cluts = set()
    for atc in alphanum_tile_codes:
        cluts = fg_tile_cluts.get(atc)
        if cluts:
            used_cluts.update(cluts)

    # now set cluts for all alphanum tiles
    for atc in alphanum_tile_codes:
        fg_tile_cluts[atc] = sorted(used_cluts)

    if context == "highscores":
        used_cluts = set()
        for atc in range(0x300,0x380):
            cluts = fg_tile_cluts.get(atc)
            if cluts:
                used_cluts.update(cluts)
        for atc in range(0x300,0x380):
            fg_tile_cluts[atc] = sorted(used_cluts)

    for i,tsd in fg_tile_sheet_dict.items():
        _,tile_set = load_tileset(tsd,i,8,8,"fg_tiles"/pathlib.Path(context) ,dump_dir,dump=dump_it,
        cluts=fg_tile_cluts,
        name_dict=None)

        for j,tile in enumerate(tile_set):
            tp = set()
            if tile:
                tile_set[j] = tile

        fg_tile_set_list.append(tile_set)

    # pad
    fg_tile_palette = quantize_image_sets(fg_tile_set_list,16-1,f"{context} fg_tiles",remove_color=magenta)

    # put magenta first (HW sprite!)
    fg_tile_palette.insert(0,magenta)


    print(f"Used fg tile colors: {len(fg_tile_palette)}")

    # pad to 16 colors
    for p in [fg_tile_palette]:
        p += (16-len(p)) * [(0x10,0x20,0x30)]

    fg_tile_plane_cache = {}
    fg_tile_table,next_id = read_tileset(fg_tile_set_list,fg_tile_palette,[True,False,False,False],cache=fg_tile_plane_cache, is_bob=False, nb_cluts=FG_NB_CLUTS, mask_color=magenta)


    bank = bank_dir / f"{context}_fg_tiles.68k"
    with open(bank,"w") as f:
        f.write("fg_tile_palette:\n")
        bitplanelib.palette_dump(fg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)

        # map layer is special, included in exe, no need to relocate
        dump_tile_layer(f,fg_tile_table,"fg",relative_root="fg_character_table")
        dump_plane_cache(f,"tile_plane",fg_tile_plane_cache)


    asm2bin(bank)

# title is special: there are no tiles or sprites. Actually there are but it's much faster & efficient
# to store a big pic made of tiles & sprites for the repository and also to display in-game with single blit

title_pic = Image.open(sheets_path / "title.png")
title_palette = bitplanelib.palette_extract(title_pic)
title_bitplane_data = bitplanelib.palette_image2raw(title_pic,None,title_palette,generate_mask=True,mask_color=magenta)
if len(title_palette)>16:
    raise Exception("image colors > 16!")
palette_pad(title_palette,16)

title_plane_cache = {}
full_title,next_cache_id = split_bitplane_data(title_bitplane_data,4+1,title_plane_cache,title_pic.size[0]//8 + 2,
                            title_pic.size[1],0,0)

bank = bank_dir / f"title_pic.68k"
with open(bank,"w") as f:
    f.write("title_palette:\n")
    f.write(f"\t.word\t4   | nb_bitplanes\n")
    bitplanelib.palette_dump(title_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("title_pic:\n")
    f.write("\t.word\t{width},{height}  | width (bytes),height\n".format(**full_title))
    for bid in full_title["bitplanes"]:
        f.write(f"\t.long\tbitplane_{bid:02d}-title_pic\n")
    dump_plane_cache(f,"bitplane",title_plane_cache)
    asm2bin(bank)

# background tiles & sprite contexts
context_list = bg_tile_context_list

for context in context_list:

    bg_tile_sheet_dict = {i:Image.open(sheets_path / "bg_tiles" / context / f"pal_{i:02x}.png") for i in range(BG_NB_CLUTS)}
    bg_tile_cluts = {}
    read_used_tiles(pathlib.Path(context)/"bg_used_tiles",bg_tile_cluts,BG_NB_TILES,BG_NB_CLUTS)

    bg_tile_set_list = []

    for i,tsd in bg_tile_sheet_dict.items():
        tp,tile_set = load_tileset(tsd,i,16,16,"bg_tiles" / pathlib.Path(context) ,dump_dir,dump=dump_it,
        cluts=bg_tile_cluts,
        name_dict=None)

        bg_tile_set_list.append(tile_set)


    bg_tile_palette = quantize_image_sets(bg_tile_set_list,max_used_nb_bg_tile_colors,f"{context} bg_tiles")

    palette_pad(bg_tile_palette,max_nb_bg_tile_colors)

    print(f"{context}: Used bg tile colors: {len(bg_tile_palette)}")
    if dump_it:
        sdump_dir = dump_dir / "bg_tiles"
        sdump_dir.mkdir(exist_ok=True)
        with open(sdump_dir / f"used_sprites_{context}.json","w") as f:
            bg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in bg_tile_cluts.items() if v}
            json.dump(bg_tile_cluts_dict,f,indent=2)

    bg_tile_plane_cache = {}
    bg_tile_table,_ = read_tileset(bg_tile_set_list,bg_tile_palette,[True,False,False,False],cache=bg_tile_plane_cache,
    is_bob=False, nb_cluts=BG_NB_CLUTS, mask_color=(0,0,0))


    bank = bank_dir / f"{context}_bg_tiles.68k"
    with open(bank,"w") as f:
        f.write("bg_tile_palette:\n")
        bitplanelib.palette_dump(bg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)

        dump_tile_layer(f,bg_tile_table,"bg",relative_root="bg_character_table")
        dump_plane_cache(f,"tile_plane",bg_tile_plane_cache)


    asm2bin(bank)


###############
# sprites
###############


context_list = sprite_context_list


for context in context_list:
    bob_plane_cache = {}
    sprite_palette = set()
    sprite_set_list = []
    sprite_cluts = {}
    size_table = {}
    pcontext = pathlib.Path(context)
    sprite_sheet_dict = {i:Image.open(sheets_path / "sprites" / pcontext / f"pal_{i:02x}.png") for i in range(SPRITE_NB_CLUTS)}



    # logging has a tendency to log tiles with sizes 1 & 2 when it's only 2. Why?
    # not really a problem, there are only a few exceptions, let's correct this here
    for forced_multi_size in force_multi_size_list:
        size_table[forced_multi_size] = 3

    read_used_tiles(pcontext/"used_sprites",sprite_cluts,SPRITE_NB_TILES,SPRITE_NB_CLUTS,size_table)


    if dump_it:
        sdump_dir = dump_dir / "sprites"
        sdump_dir.mkdir(exist_ok=True)
        with open(sdump_dir / f"used_sprites_{pcontext}.json","w") as f:
            sprite_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in sprite_cluts.items() if v}
            json.dump({"cluts":sprite_cluts_dict,"sizes":{hex(k):v for k,v in size_table.items()}},f,indent=2)

    # correct incorrectly logged size (why??)

    for k,v in sprite_names.items():
        # all player 1 frames for player 2 in all contexts
        if v.startswith("player"):
            # can't just force 0,1 as green punk uses most of player frames
            existing = set(sprite_cluts.get(k) or [])
            # we have to make sure that player 1 frame exists else double size
            # and green punk define cluts where the rest of the python code doesn't expect
            # and we get errors with multi-sized tiles. I don't want to debug that crap
            # Leave the game log only the proper tiles
            if 0 in existing:
                existing.add(1)
                sprite_cluts[k] = existing



    for i,tsd in sprite_sheet_dict.items():
        tp,tile_set = load_tileset(tsd,i,16,16,"sprites" / pcontext,dump_dir,dump=dump_it, cluts=sprite_cluts,
        name_dict=get_sprite_names(),
        is_bob=True,
        size_table=size_table)
        sprite_set_list.append(tile_set)

    # compute palette & apply quantization if needed
    sprite_palette = quantize_image_sets(sprite_set_list,max_used_nb_sprite_colors,image_type="sprite",remove_color=magenta)

    palette_pad(sprite_palette,max_nb_sprite_colors)
    empty_32_cols = []
    palette_pad(empty_32_cols,max_nb_bg_tile_colors)

    sprite_table,_ = read_tileset(sprite_set_list,empty_32_cols+sprite_palette,[True,False,False,False],cache=bob_plane_cache, is_bob=True, mask_color=magenta, nb_cluts=SPRITE_NB_CLUTS)
    bank = bank_dir / f"{context}_sprites.68k"
    with open(bank,"w") as f:
        f.write("sprite_palette:\n")
        bitplanelib.palette_dump(sprite_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
        dump_bob_layer(sprite_table,f,relative_root="bob_table")
    asm2bin(bank)

if context_list:
    print(f"Used sprite colors: {len(sprite_palette)}")



# sprite_set_list is now a 16x512 matrix of sprite tiles


#fg_tile_lower_table,_ = read_tileset(fg_tile_lower_set_list,fg_tile_lower_palette,[True,False,False,False],cache=tile_plane_cache, is_bob=False, nb_cluts=FG_NB_CLUTS, mask_color=magenta, next_cache_id = next_id)
#sprite_table,_ = read_tileset(sprite_set_list,empty_32_cols+sprite_palette,[True,False,False,False],cache=bob_plane_cache, is_bob=True, mask_color=magenta, nb_cluts=SPRITE_NB_CLUTS)


##
##BLOCK_DISPLAY_MASK = 1<<14
##DO_DISPLAY_MASK = 1
##
##def gen_codes(i):
##    im = (i<<1)
##    return im | DO_DISPLAY_MASK,(0x800 + im) | DO_DISPLAY_MASK
##
##gs_array = [0]*SPRITE_NB_TILES
##for i in group_sprite_pairs:
##    gs_array[i],gs_array[i+1] = gen_codes(i)
##
##for i in group_sprite_triplets:
##    gs_array[i],gs_array[i+2] = gen_codes(i)
##    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
##for i in group_sprite_quadruplets:
##    gs_array[i],gs_array[i+3] = gen_codes(i)
##    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
##    gs_array[i+2] = BLOCK_DISPLAY_MASK    # never display alone!

##used_sprite_codes = set(sprite_cluts) | {i for i,g in enumerate(gs_array) if g}
##unused_sprite_codes = set(range(0,SPRITE_NB_TILES))-used_sprite_codes
### it's normal that some sprite codes aren't used at all
##print("Unused sprite codes: {}".format(",".join(sorted(f"0x{x:03x}" for x in unused_sprite_codes))))
##
##with open(src_dir / "sprite_groups.68k","w") as f:
##    f.write(generated_message)
##    f.write("* see amiga.68k display_one_bob routine to know how this works\n")
##
##    bitplanelib.dump_asm_bytes(gs_array,f,mit_format=True,size=2)
##
##




